### ISSUE TITLE
On connection close event

### ISSUE THREAD

**Issue by tomas-berg** [medooze/sfu#5]
Could you please advice best practice to catch event when remote peer is closed connection?
I'm implementing simple SFU server and need to know when client peer is leaving the room. How do I catch it in proper way?

Thanks in advance.

**Comment by murillo128** [comment]
I do it like this:

https://github.com/medooze/sfu/blob/master/index.js#L217

You rely on the ws disconnect event, so either you enable the ws keepalive or you would rely on tcp timeouts for abrupt disconnections

**Comment by tomas-berg** [comment]
@murillo128 Thanks for your reply.
I'm afraid relying on ws signaling is a bad idea in my case. Would be extremely nice to have event fired up on peer connection close. So, when client (browser) closes the tab, I need to catch this event and delete user from the room.

**Comment by murillo128** [comment]
I don't think that is currently possible. There are two ways of improving the behavior of the media server, which have planned for a while:

- Adding and event on DTLS shutdown (https://github.com/medooze/media-server-node/issues/42)
- Adding ICE ping/keep-alive stats at Transport level (https://github.com/medooze/media-server-node/issues/43)

**Comment by tomas-berg** [comment]
Thanks, Sergio. Looking forward for updates.
